# Generated by Django 2.1.5 on 2019-01-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='标题')),
                ('content', models.CharField(max_length=10000, verbose_name='内容')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
                ('keyword', models.CharField(max_length=100, verbose_name='关键字')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.CharField(max_length=20, unique=True, verbose_name='栏目编码')),
                ('sort', models.CharField(max_length=20, unique=True, verbose_name='栏目编号')),
                ('c', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='article.Column', verbose_name='栏目')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='a',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='article.Column', verbose_name='文章'),
        ),
    ]
