# Generated by Django 2.1.5 on 2019-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='a',
        ),
        migrations.RemoveField(
            model_name='column',
            name='c',
        ),
        migrations.AlterField(
            model_name='column',
            name='sort',
            field=models.CharField(max_length=20, unique=True, verbose_name='栏目分类名称'),
        ),
    ]
